### ISSUE TITLE
Takes too much VRAM to transcribe audios

### ISSUE THREAD

**Issue by PS-AI** [nyrahealth/CrisperWhisper#13]
Hi,

Thank you for your work.  

I tested CrisperWhisper today with an audio of 2 minute duration on a NVIDAI A100 GPU.  The model VRAM footprint is only 3.5GB which is great. However, when processing a 2 minute audio, I get a CUDA out of memory error as the GPU usage goes above 40 GB. 

Is this something that will be fixed soon.  If not, what would be the best solution to handle long audios.

**Comment by PS-AI** [comment]
Thank you for your response.  I have given my code below.

I am running it in google Collab on a A100 GPU.  I am using the same code that you sent after installing required libraries and logging into HuggingFace.  I get a CUDA OOM error when transcribing a 2 minute audio.

!pip install torch torchaudio
!pip install transformers
!pip install accelerate
!huggingface-cli login

#From Laurin
import os
import sys
import torch

#from datasets import load_dataset
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
#from utils import adjust_pauses_for_hf_pipeline_output

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "nyrahealth/CrisperWhisper"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
"automatic-speech-recognition",
model=model,
tokenizer=processor.tokenizer,
feature_extractor=processor.feature_extractor,
chunk_length_s=30,
batch_size=16,
return_timestamps='word',
torch_dtype=torch_dtype,
device=device,
)
hf_pipeline_output = pipe('/content/2min.wav')
print(hf_pipeline_output)

**Comment by smoothdvd** [comment]
Same on A100 80G:
An error occurred while transcribing the audio: CUDA out of memory. Tried to allocate 768.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 164.75 MiB is free. Including non-PyTorch memory, this process has 78.97 GiB memory in use. Of the allocated memory 73.51 GiB is allocated by PyTorch, and 4.96 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by LaurinmyReha** [comment]
okay, lowering the batch size ( for example 1 in the extreme case) to fit your GPU size and/or adjusting the beam size should resolve your issue. Could you try this out and let me know how it went? 

number of beams you can adjust by using the generate_kwargs argument:
`hf_pipeline_output = pipe('/content/2min.wav', generate_kwargs = {"num_beams": 1})`

**Comment by darnn** [comment]
With the code below, a batch size of 1 gives the following error:
`RuntimeError: The expanded size of the tensor (4) must match the existing size (5) at non-singleton dimension 0.  Target sizes: [4].  Tensor sizes: [5]`
With a batch size of 2:
`RuntimeError: The expanded size of the tensor (6) must match the existing size (7) at non-singleton dimension 0.  Target sizes: [6].  Tensor sizes: [7]`
With a batch size of 3:
`RuntimeError: The expanded size of the tensor (7) must match the existing size (8) at non-singleton dimension 0.  Target sizes: [7].  Tensor sizes: [8]`
With a batch size of 4, it gives the out of memory error:
`OutOfMemoryError: CUDA out of memory. Tried to allocate 104.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 9.12 MiB is free. Process 20315 has 15.88 GiB memory in use. Of the allocated memory 14.53 GiB is allocated by PyTorch, and 1.06 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

Here's the code. It's as above, except with `generate_kwargs = {"num_beams": 1}`:

import os
import sys
import torch

from datasets import load_dataset
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from utils import adjust_pauses_for_hf_pipeline_output



device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "nyrahealth/CrisperWhisper"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    chunk_length_s=10,
    batch_size=4,
    return_timestamps='word',
    torch_dtype=torch_dtype,
    device=device,
)

dataset = load_dataset("distil-whisper/librispeech_long", "clean", split="validation")
sample = dataset[0]["audio"]
hf_pipeline_output = pipe("/kaggle/input/idkuney/idkuney.aac", generate_kwargs = {"num_beams": 1})
crisper_whisper_result = adjust_pauses_for_hf_pipeline_output(hf_pipeline_output)
print(crisper_whisper_result)

**Comment by lokesh12345678910** [comment]
fwiw, the code worked on google colab when I didn't use a gpu (but obviously very slow), make sure to click high-ram though just in case

**Comment by siddhsql** [comment]
same problem here. i tried on WSL2 with 16GB RAM total. my code is this:

```
import os
import sys
import torch

from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from utils import adjust_pauses_for_hf_pipeline_output

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "nyrahealth/CrisperWhisper"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    chunk_length_s=30,
    batch_size=16,
    return_timestamps='word',
    torch_dtype=torch_dtype,
    device=device,
)

file_path = "/path/to/audio.aac"

result = pipe(file_path)
```

and it gives a OOM. i have made sure whole 16GB is available to WSL2.

```
$ dmesg | grep -i 'oom'
[  415.476978] snapfuse invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[  415.484934]  oom_kill_process.cold+0xb/0x10
[  415.488176] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[  415.488617] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=python3,pid=1490,uid=1000
[  415.489352] Out of memory: Killed process 1490 (python3) total-vm:23909940kB, anon-rss:15532164kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:39964kB oom_score_adj:0
```

i see these messages but don't think it has to do with OOM:

```
/CrisperWhisper/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WhisperModel is using WhisperSdpaAttention, but `torch.nn.functional.scaled_dot_product_attention` does not support `output_attentions=True` or `layer_head_mask` not None. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.
```

**Comment by mcashm** [comment]
Seeing the same: out of memory with GPUs and the "Special tokens" warning @siddhsql mentions.

**Comment by TinaTe** [comment]
Any news on this? It seems puzzling, that some people are obviously using this, but others (including me) can't even get it to finish a very small sample, which is quite frustrating since this model is the only one I know of that focuses on full verbatim transcription.

**Comment by rafal01010** [comment]
Seeing the same. Do ASR models generally use that much more VRAM for long audios?

**Comment by MatsPro** [comment]
I experience the same problem with OOM on a macbook m1 pro 16GB. Tried with batches 8/16

**Comment by TinaTe** [comment]
Hi all, 
I don't know whether this helps, but I got the faster-whisper version of this model to run within whisperx. It's pretty slow, but for my usecase, I don't really care. So far it looks good, but I haven't had the time to do an exhaustive evaluation on whether it performs better than other models with a prompt.

**Comment by darnn** [comment]
@TinaTe Can you comment on any improvement in the accuracy of the timing, and on whether it even works with languages that aren't English?
And also, would you mind posting the code you used?

**Comment by TinaTe** [comment]
@darnn Unfortunately I didn't have the time to test it systematically yet. Codewise, I basically used it like it's described in [whisperx](https://github.com/m-bain/whisperX), but I downloaded the model from [huggingface](https://huggingface.co/nyrahealth/faster_CrisperWhisper/tree/main) beforehand (sensitive data). 

`import whisperx
import gc 

device = "cuda" 
audio_file = "audio.mp3"
batch_size = 16 
compute_type = "float16"
transcription_model = "path/to/the/model"

model = whisperx.load_model(transcription_model, device, compute_type=compute_type)
audio = whisperx.load_audio(audio_file)

result = model.transcribe(audio, batch_size=batch_size)`

**Comment by semidark** [comment]
I think I have a similar Problem. 

```shell
$ nvidia-smi
Tue Mar 18 10:20:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000001:00:00.0 Off |                  Off |
| N/A   29C    P8             13W /   70W |       3MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
$ PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python transcribe.py --f  video1079151971.mp3
/home/ubuntu/.local/miniforge3/envs/crisper-whisper/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WhisperModel is using WhisperSdpaAttention, but `torch.nn.functional.scaled_dot_product_attention` does not support `output_attentions=True` or `layer_head_mask` not None. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.
An error occurred while transcribing the audio: CUDA out of memory. Tried to allocate 294.00 MiB. GPU 0 has a total capacity of 15.56 GiB of which 104.62 MiB is free. Including non-PyTorch memory, this process has 15.45 GiB memory in use. Of the allocated memory 15.30 GiB is allocated by PyTorch, and 31.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 
```

**Comment by ilovefreesw** [comment]
![Image](https://github.com/user-attachments/assets/a14d2c2a-1c8a-43ab-823e-47bc010ef5b1)

**Comment by vcBinary** [comment]
First, I would like to thank the creators of this model. I think it is awesome! 
@LaurinmyReha @BernhardThNyra 

I had the same issue as everyone commenting here. The way I solved it this by configuring the `AutoModelForSpeechSeq2Seq` with the parameter `use_cache` (which, by default, is set to True) to False and keeping the `batch_size` of the transformer's `pipeline` to a low number.

Like this:
```python
model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True, use_cache=False
)
```
It seems like the caching size is not limited, and it keeps growing until the program crashes with **"CUDA out of memory"**.

Being a common issue, I think it would probably be a good idea to mention it somewhere in the `README.md` or change the default value of the parameter `use_cache` to `false` in the `config.json` of this model's HuggingFace's repository.

**Comment by lokesh12345678910** [comment]
@vcBinary  This solution worked for me!
